// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mi_proyecto_sena.Data;

#nullable disable

namespace mi_proyecto_sena.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20251114053853_migracion_003")]
    partial class migracion_003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mi_proyecto_sena.Models.usuarioModel", b =>
                {
                    b.Property<int>("usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("usuario_Id"));

                    b.Property<string>("usuario_Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario_contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario_correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario_sait")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("usuario_Id");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
